apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-cicd
  labels:
    app: first-cicd
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-cicd
  template:
    metadata:
      labels:
        app: first-cicd
    spec:
      containers:
        - name: first-cicd
          image: azureforbeginner.azurecr.io/image-sample-1711943921860:latest
          ports:
            - containerPort: 5000