apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampledemo
  labels:
    app: sampledemo
  namespace: namespace-workflow-1711357692801
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampledemo
  template:
    metadata:
      labels:
        app: sampledemo
    spec:
      containers:
        - name: sampledemo
          image: leefernz.azurecr.io/image-workflow-1711357692801:latest
          ports:
            - containerPort: 5000