apiVersion: v1
kind: Service
metadata:
  name: firstdemo
  namespace: namespace-workflow-1711352276420
spec:
  type: LoadBalancer
  selector:
    app: firstdemo
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000