apiVersion: v1
kind: Service
metadata:
  name: first-cicd
  namespace: demo
spec:
  type: LoadBalancer
  selector:
    app: first-cicd
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000