apiVersion: v1
kind: Service
metadata:
  name: sampledemo
  namespace: namespace-workflow-1711357692801
spec:
  type: LoadBalancer
  selector:
    app: sampledemo
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000